name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Cython and other Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install buildozer
        pip install kivymd kivy requests

    - name: Make gradlew executable
      run: |
        # Create buildozer directory if it doesn't exist
        mkdir -p ~/.buildozer

    - name: Build APK with Buildozer
      run: |
        # Set environment variables
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        
        # Accept Android licenses
        yes | sdkmanager --licenses
        
        # Install required Android SDK components
        sdkmanager "platforms;android-31"
        sdkmanager "build-tools;31.0.0"
        sdkmanager "ndk;25.2.9519653"
        
        # Build APK
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpellChecker-APK
        path: bin/*.apk
        if-no-files-found: error

    - name: List build files (for debugging)
      if: always()
      run: |
        echo "Contents of current directory:"
        ls -la
        echo "Contents of bin directory (if exists):"
        ls -la bin/ || echo "bin directory not found"
        echo "Contents of .buildozer directory:"
        ls -la .buildozer/ || echo ".buildozer directory not found"